name: Set up .NET
description: Sets up the .NET SDK.

inputs:
  dotnet-version:
    required: false
    default: 8.0.301
    description: Version of the .NET SDK to set up.

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Set Environment Variables
      shell: pwsh
      run: |
        Set-GitHubEnv 'DOTNET_SKIP_FIRST_TIME_EXPERIENCE' 'true'
        Set-GitHubEnv 'DOTNET_CLI_TELEMETRY_OPTOUT' 'true'

    # This makes builds faster under Windows, see
    # https://github.com/actions/setup-dotnet/issues/260#issuecomment-2516145018. Only GitHub-hosted standard (not
    # larger) runners have such a D drive.
    - name: Set DOTNET_INSTALL_DIR on Windows
      if: runner.os == 'Windows' && !contains(runner.name, 'core_') && !contains(runner.name, 'warp')
      shell: pwsh
      run: |
        Set-GitHubEnv 'DOTNET_INSTALL_DIR' 'D:\dotnet'
        Set-GitHubEnv 'NUGET_PACKAGES' 'D:\a\.nuget\packages'

    # For wildcard .NET versions, the General Availability ("ga") channel should be selected. For concrete versions,
    # this shouldn't be set, because that'll cause a warning.
    - name: Set dotnet-quality
      id: set-dotnet-quality
      shell: pwsh
      run: |
        if ('${{ inputs.dotnet-version }}' -match 'x')
        {
            Set-GitHubOutput 'dotnet-quality' 'ga'
        }

    # setup-dotnet won't install a version if it is already preinstalled on the VM. Note that it checks the latest
    # released .NET version for wildcard versions. So, e.g. with 6.0.x specified it'll still install 6.0.402 if the VM
    # only has 6.0.401. See: https://github.com/actions/setup-dotnet/issues/356 about making this better.
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4.0.0
      id: setup-dotnet
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ steps.set-dotnet-quality.outputs.dotnet-quality }}

    - name: Save .NET SDK Version Into Environment Variable
      shell: pwsh
      run: |
        Set-GitHubEnv 'DOTNET_SDK_TO_USE' ${{ steps.setup-dotnet.outputs.dotnet-version }}
